# Generated by Django 5.0.3 on 2024-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('deviceId', models.AutoField(primary_key=True, serialize=False)),
                ('deviceName', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('deviceType', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
